# ----------------------------
# Makefile Options
# ----------------------------

NAME = VIDEO
ICON = icon.png
DESCRIPTION = "video player with usb"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
